AltTexture{
    key = "static_jokers",
    set = "Joker",
    path = "AGGLOMERATION1.png",
    original_sheet = false,
    keys = {
        'j_8_ball',
        'j_mr_bones',
        'j_sixth_sense',
        'j_stencil',
        'j_wee',
        'j_photograph',
        'j_diet_cola',
        'j_ice_cream',
        'j_gros_michel',
        'j_castle',
        'j_cavendish',
        'j_selzer',
        'j_hanging_chad',
        'j_scary_face',
        'j_acrobat',
        'j_abstract',
        'j_matador',
        'j_ride_the_bus',
        'j_blueprint',
        'j_business',
        'j_devious',
        'j_luchador',
        'j_swashbuckler',
        'j_mail',
        'j_hologram',
        'j_space',
        'j_satellite',
        'j_delayed_grat',
        'j_faceless',
        'j_boostraps',
        'j_vagabond',
        'j_smiley',
        'j_trousers',
        'j_cloud_9',
        'j_joker',
        'j_ring_master',
        'j_mime',
        'j_even_steven',
        'j_sock_and_buskin',
        'j_steel_joker',
        'j_to_the_moon',
        'j_sly',
        'j_greedy_joker',
        'j_ticket',
        'j_bull',
        'j_troubadour',
        'j_dna',
        'j_cartomancer',
        'j_glass',
        'j_stuntman',
        'j_four_fingers',
        'j_walkie_talkie',
        'j_trading',
        'j_flash',
        'j_juggler',
        'j_seeing_double',
        'j_drunkard',
        'j_certificate',
        'j_credit_card',
        'j_square',
        'j_shortcut',
        'j_blackboard',
        'j_pareidolia',
        'j_ancient',
        'j_midas_mask',
        'j_banner',
        'j_oops',
    }
}

TexturePack{
    key = "malskin",
    textures = {
        'uncardable_static_jokers',
    },
    loc_txt = {
        name = "UNCARDABLE Malverk",
        text = {'Malverk variant of UNCARDABLE joker reskins'}
    }
}